# Generated by Django 4.1.3 on 2022-12-02 08:02

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to=website.models.upload_Certificate_to),
        ),
    ]
